# Import pandas and the csv file

In [2]:
import pandas as pd

airbnb_test_users = pd.read_csv("airbnb_test_users.csv")

airbnb_test_users.head(10)

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari
5,szx28ujmhf,7/1/2014,2.014070e+13,NaN,FEMALE,28.0,basic,0,en,sem-brand,google,omg,Web,Windows Desktop,Chrome
6,guenkfjcbq,7/1/2014,2.014070e+13,NaN,MALE,48.0,basic,25,en,direct,direct,untracked,iOS,iPhone,-unknown-
7,tkpq0mlugk,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome
8,3xtgd5p9dn,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome
9,md9aj22l5a,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,sem-non-brand,google,omg,Web,Windows Desktop,Firefox

# Q1. What is the average age of those who use each web browser type?

# Use aggregate function to calculate mean of age groupby first_browser

In [5]:
airbnb_test_users.groupby('first_browser')['age'].mean()

first_browser
-unknown-             41.526894
AOL Explorer          60.000000
Android Browser       42.822148
Apple Mail            26.750000
BlackBerry Browser    34.600000
Chrome                34.591678
Chrome Mobile         45.199058
Chromium              28.833333
CometBird             30.000000
Firefox               37.748143
IBrowse               51.000000
IE                    42.463107
IE Mobile             32.312500
IceWeasel             18.000000
Iron                  35.200000
Maxthon               31.000000
Mobile Firefox        31.800000
Mobile Safari         35.098486
Nintendo Browser            NaN
Opera                 38.444444
Opera Mini                  NaN
Opera Mobile          37.000000
Pale Moon             37.000000
Safari                36.416121
SeaMonkey                   NaN
Silk                  38.120000
SiteKiosk             57.000000
Sogou Explorer        28.000000
UC Browser            28.000000
Yandex.Browser        38.500000
wOSBrowser                  NaN
Name: age, dtype: float64

# Q2. What is the total signup_flow for each device?

# Use aggregate function to calculate sum of signup_flow groupby first_device_type

In [6]:
airbnb_test_users.groupby('first_device_type')['signup_flow'].sum()

first_device_type
Android Phone          90521
Android Tablet          5969
Desktop (Other)           50
Mac Desktop             5736
Other/Unknown           4826
SmartPhone (Other)         0
Windows Desktop         3866
iPad                   28900
iPhone                345343
Name: signup_flow, dtype: int64

# 1. They need the country information from the airbnb_sample_submission dataset included in the airbnb_test_users file.

In [7]:
#import the airbnb_sample_submission csv file

airbnb_sample_submission = pd.read_csv("airbnb_sample_submission.csv")

airbnb_sample_submission.head()

           id country
0  5uwns89zht     NDF
1  jtl0dijy2j     NDF
2  xx0ulgorjt     NDF
3  6c6puo6ix0     NDF
4  czqhjk3yfe     NDF

# To include country information, we need to join/ merge the two data sets based on the id

In [8]:
airnbnb_w_country = pd.merge(airbnb_test_users, airbnb_sample_submission, how='inner')

In [9]:
airnbnb_w_country.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE,NDF
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari,NDF

# 2. Add additional users to the test file from the airbnb_users dataset.

In [11]:
#import the airbnb_users csv file

airbnb_users = pd.read_csv("airbnb_users.csv")

In [12]:
# To add users from the above file, in the test file use concat function

airnbnb_users_country = pd.concat([airnbnb_w_country, airbnb_users])

In [15]:
airnbnb_users_country.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country,country_destination
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF,NaN
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF,NaN
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF,NaN
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE,NDF,NaN
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari,NDF,NaN

id                         275547
date_account_created       275547
timestamp_first_active     275547
date_first_booking          88908
gender                     275547
age                        158681
signup_method              275547
signup_flow                275547
language                   275547
affiliate_channel          275547
affiliate_provider         275547
first_affiliate_tracked    269462
signup_app                 275547
first_device_type          275547
first_browser              275547
country                     62096
country_destination        213451
dtype: int64